-- Production Database Schema for Profile Nano Banana
-- Use this SQL to set up the new production project in Supabase.

-- 1. Create profiles table
-- Tracks user credits, subscription status, and Stripe customer ID.
create table if not exists profiles (
  email text primary key,
  credits int default 5, -- Give 5 free credits on signup
  stripe_customer_id text,
  subscription_tier text, -- 'free', 'basic', 'pro', 'premium'
  subscription_status text, -- 'active', 'canceled', 'past_due'
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Create generations table
-- Stores history of generated images.
create table if not exists generations (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_email text not null,
  prompt text,
  scene text,
  images text[] -- Array of base64 strings
);

-- 3. Enable Row Level Security (RLS)
-- Recommended for security, even if using Service Role Key on the server.
alter table profiles enable row level security;
alter table generations enable row level security;

-- 4. Create RLS Policies
-- Since we primarily use the Service Role Key in the Next.js API routes, these policies
-- are mainly for if you ever access Supabase from the client-side directly.
-- For now, we can allow users to read their own data.

-- Profiles: Users can read their own profile
create policy "Users can view own profile"
  on profiles for select
  using ( auth.jwt() ->> 'email' = email );

-- Generations: Users can read their own generations
create policy "Users can view own generations"
  on generations for select
  using ( user_email = auth.jwt() ->> 'email' );

-- Note: Insert/Update is handled via API with Service Role, so no public write policies needed yet.
