-- Create profiles table to track user credits and subscriptions
create table if not exists profiles (
  email text primary key,
  credits int default 5, -- Give 5 free credits on signup
  stripe_customer_id text,
  subscription_tier text, -- 'free', 'basic', 'pro', 'premium'
  subscription_status text, -- 'active', 'canceled', 'past_due'
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create generations table to store generation history
create table if not exists generations (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_email text not null,
  prompt text,
  scene text,
  images text[] -- Array of base64 strings
);

-- Enable Row Level Security (Optional but recommended, though we use Service Role Key in API)
alter table profiles enable row level security;
alter table generations enable row level security;

-- Create policies (Optional, if you plan to use client-side Supabase)
-- For now, since we use server-side API with service role, these aren't strictly needed for the app to work,
-- but good practice.
